---
#=========================================================
# Build System Data Container
#---------------------------------------------------------
- name: Build docker image ----- Test Station build system data
  docker_image:
    name: "{{ name_prefix }}teststation_http_data_buildsystem_image"
    path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_http_data_buildsystem.dir_name }}"
    state: "{{ image_build_state_data }}"
    force: "{{ docker_image_force_build }}"

- name: Start docker container - Test Station build system data
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_http_data_buildsystem_image"
    name: "{{ name_prefix }}TestStation_http_data_buildsystem"
    state: "{{ container_start_state_data }}"
