---
#=========================================================
# Production SSH Server Container
#---------------------------------------------------------
- name: Setting root user password, for the bs prod ssh docker container
  replace:
    dest: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_ssh_server_manualtest.dir_name }}/Dockerfile"
    regexp: "root_user_password"
    replace: '{{ buildsystem_ssh_root_user_password }}'

- name: Setting additional user password, for the bs prod ssh docker container
  replace:
    dest: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_ssh_server_manualtest.dir_name }}/Dockerfile"
    regexp: "some_additional_user_password"
    replace: '{{ buildsystem_ssh_prod_user_password }}'

- name: Setting additional user name, for the bs prod ssh docker container
  replace:
    dest: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_ssh_server_manualtest.dir_name }}/Dockerfile"
    regexp: "some_additional_user"
    replace: '{{ buildsystem_ssh_prod_user_name }}'

- name: Build docker image ----- Test Station production ssh server temp.
  docker_image:
    name: "{{ name_prefix }}teststation_ssh_server_manualtest_image"
    path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_ssh_server_manualtest.dir_name }}"
    state: "{{ image_build_state_nondata }}"

- name: Start docker container - Test Station production ssh server temp.
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_ssh_server_manualtest_image"
    name: "{{ name_prefix }}TestStation_ssh_server_manualtest"
    ports: "{{ container_addr_map.testssh.ip_addr }}:22:22"
    state: "{{ container_start_state_nondata }}"
    restart_policy: '{{ docker_restart_policy }}'
