---
#=========================================================
# HTTP Server Container
#---------------------------------------------------------
- name: Build docker image ----- Test Station http server
  docker_image:
    name: "{{ name_prefix }}teststation_http_image"
    path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_http_server.dir_name }}"
    state: "{{ image_build_state_nondata }}"

- name: Start docker container - Test Station http server
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_http_image"
    links: "{{ name_prefix }}TestStation_database_server:test_station_mysql_server"
    name: "{{ name_prefix }}TestStation_http_server"
    ports: "{{ build_ip_addr }}:80:80"
    state: "{{ container_start_state_nondata }}"
    restart_policy: '{{ docker_restart_policy }}'
    volumes_from:
      - "{{ name_prefix }}TestStation_http_data_buildsystem"
#      - "{{ name_prefix }}TestStation_http_data_ipkg"
      - "{{ name_prefix }}TestStation_http_data_ncdiso"
      - "{{ name_prefix }}TestStation_http_data_ncdrelease"
      - "{{ name_prefix }}TestStation_http_data_testclient"
      - "{{ name_prefix }}TestStation_tftp_data"
