---
#=========================================================
# SSH Server Container
#---------------------------------------------------------
- name: Setting root user password, for the bs prod ssh docker container
  replace:
    dest: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_ssh_server.dir_name }}/Dockerfile"
    regexp: "root_user_password"
    replace: '{{ buildsystem_ssh_root_user_password }}'

- name: Build docker image ----- Test Station ssh server
  docker_image:
    name: "{{ name_prefix }}teststation_ssh_image"
    path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_ssh_server.dir_name }}"
    state: "{{ image_build_state_nondata }}"

- name: Start docker container - Test Station ssh server
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_ssh_image"
    links: "{{ name_prefix }}TestStation_database_server:test_station_mysql_server"
    name: "{{ name_prefix }}TestStation_ssh_server"
    ports: "{{ container_addr_map.build.ip_addr }}:22:22"
    restart_policy: '{{ docker_restart_policy }}'
    state: "{{ container_start_state_nondata }}"
    volumes_from:
      - "{{ name_prefix }}TestStation_database_data"
      - "{{ name_prefix }}TestStation_http_data_buildsystem"
#      - "{{ name_prefix }}TestStation_http_data_ipkg"
      - "{{ name_prefix }}TestStation_http_data_ncdiso"
      - "{{ name_prefix }}TestStation_http_data_ncdrelease"
      - "{{ name_prefix }}TestStation_http_data_testclient"
      - "{{ name_prefix }}TestStation_tftp_data"
