---
#=========================================================
# TFTP Server Container
#---------------------------------------------------------
- name: Build docker image ----- Test Station tftp server
  docker_image:
    name: "{{ name_prefix }}teststation_tftp_image"
    path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_tftp_server.dir_name }}"
    state: "{{ image_build_state_nondata }}"

- name: Start docker container - Test Station tftp server
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_tftp_image"
    name: "{{ name_prefix }}TestStation_tftp_server"
    ports: "{{ build_ip_addr }}:69:69/udp"
    state: "{{ container_start_state_nondata }}"
    restart_policy: '{{ docker_restart_policy }}'
    volumes_from:
      - "{{ name_prefix }}TestStation_tftp_data"
